### ISSUE TITLE
Mejoras para el positronic

### ISSUE THREAD

**Issue by agar3s** [StudioKrok/positronic.js#7]
para el positronic.js

primero configurar, es registrar el simbolo/identificador y el codigo que debe ejecuar

luego compilar pasando como parametro el codigo a ejecutar y el contexto(el juego en este caso), sobre el que se va a ejecutar.

la compilacion devuelve un objeto que ejecuta paso a paso el programa.

**Comment by mapedorr** [comment]
Solucionado en commit: 8c365b438d9c6f4ee3eab709d643b092fddc8570
